language: ruby
dist: xenial
bundler_args: "--without deployment"
sudo: required
services: mysql
addons:
  chrome: stable
  apt:
    packages:
    - haveged
    - google-chrome-stable
cache:
  bundler: true
env:
  global:
  - TZ=Europe/London
  - DISPLAY=:99.0
before_install:
- gem install bundler:1.17.3
before_script:
- bundle exec rake db:setup
- bundle exec rake webdrivers:chromedriver:update
script:
- xvfb-run -a bundle exec rspec
deploy:
  provider: releases
  file: release.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: sanger/sm_workflow_lims
  api_key:
    secure: cJalqsS+skyojjpUlZKKUwLro+pnNhKkjTXJc3y55yQboYZuGvbYiPbMtfloouWuTQGDJYz4VGSbb3+Y35OMXHD5cC9OmkuyNUefRKUL304rVSNBZvRb0KKO9iIA4mETNcRz7fQqoe27cu8/PdHlfgs/ue0N/rp7EcrPDdjmkeA=
  file: release.tar.gz
notifications:
  slack: psd-team:V2SCGvDqEvbszhvCUdTcQOKm
